# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import HelloDroidTLS_pb2 as HelloDroidTLS__pb2


class GreeterStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/hellodroidtls.Greeter/SayHello',
        request_serializer=HelloDroidTLS__pb2.HelloRequest.SerializeToString,
        response_deserializer=HelloDroidTLS__pb2.HelloReply.FromString,
        )
    self.SayHelloAgain = channel.unary_unary(
        '/hellodroidtls.Greeter/SayHelloAgain',
        request_serializer=HelloDroidTLS__pb2.HelloRequest.SerializeToString,
        response_deserializer=HelloDroidTLS__pb2.HelloReply.FromString,
        )


class GreeterServicer(object):
  """The greeting service definition.
  """

  def SayHello(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SayHelloAgain(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=HelloDroidTLS__pb2.HelloRequest.FromString,
          response_serializer=HelloDroidTLS__pb2.HelloReply.SerializeToString,
      ),
      'SayHelloAgain': grpc.unary_unary_rpc_method_handler(
          servicer.SayHelloAgain,
          request_deserializer=HelloDroidTLS__pb2.HelloRequest.FromString,
          response_serializer=HelloDroidTLS__pb2.HelloReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hellodroidtls.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
